[username]
show_always = true
style_user = "blue"
style_root = "red bold"
format = "â•­â”€â”€â”€â”€â”€[î‚²](fg:blue)[ $user ](fg:white bg:blue)[î‚°](fg:blue bg:green)"

[cmd_duration]
disabled = true

[directory]
truncation_length = 1
truncation_symbol = ""
format = "[ $path ](fg:black bg:green)[$read_only](bg:green)[î‚° ](fg:green)"

[character]
success_symbol = "[â•°ï‘ ](bold white) "
error_symbol = "[â•°ï‘ ](bold white) "

[conda]
ignore_base = false
format = "[$symbol$environment ](bright-yellow) "

[golang]
disabled = true

[python]
disabled = true

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
